install.packages("recommenderlab", repos="http://cran.r-project.org", lib="/home/ubuntu/bgse-dashboard-project/Rlibs/")
install.packages("glmnet", repos="http://cran.r-project.org", lib="/home/ubuntu/bgse-dashboard-project/Rlibs/")
install.packages("RMySQL", repos="http://cran.r-project.org", lib="/home/ubuntu/bgse-dashboard-project/Rlibs/")
install.packages("lars", repos="http://cran.r-project.org", lib="/home/ubuntu/bgse-dashboard-project/Rlibs/")
install.packages("forecast", repos="http://cran.r-project.org", lib="/home/ubuntu/bgse-dashboard-project/Rlibs/")